### ISSUE TITLE
please provide a license for this project

### ISSUE THREAD

**Issue by olamy** [aloubyansky/playground#1]
it would be nice to be able to reuse this project as an Integration test in the Apache Maven project https://github.com/apache/maven-integration-testing 
but there is currently no license.
such https://github.com/aloubyansky/playground/tree/maven-3.8.5-profile-activation
please add a license such Apache 
thanks

**Comment by aloubyansky** [comment]
Sure, just added the Apache 2.0 license to that branch. Thanks!
